#!/bin/bash

set -e

case "$1" in
    configure)
        # Add Linux Mint repository key
        apt-key --keyring /etc/apt/trusted.gpg.d/linux_mint.gpg adv --recv-keys --keyserver keyserver.ubuntu.com A6616109451BBBF2 2>1 > /dev/null
	# Adding repos via add-apt-repository
	add-apt-repository -y ppa:s-ramacher/ait > /dev/null
	add-apt-repository -y ppa:flx/chromium > /dev/null
        ;;

    *)
        ;;
esac

#DEBHELPER#

exit 0
